# КОММЕНТАРИИ
## Получение комментариев по id предложения
GET http://localhost:5000/comments/6543906d1de6e37dbe9b4c5f HTTP/1.1
###


## Создание комментария
POST http://localhost:5000/comments HTTP/1.1
Content-Type: application/json

{
  "text": "fuuuuuuuuck fffff dddddeeee",
  "rating": 2,
  "offerId": "654393628639cd2060ff00ca",
  "author": "6543977266478393a664f76c"
}
###


# ПОЛЬЗОВАТЕЛИ
## Создать нового пользователя
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Valya",
  "mail": "valya@ya.net",
  "avatar": "",
  "userType": "обычный",
  "password": "123fffff"
}
###

## Авторизация  пользователя
POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "mail": "valya@ya.net",
  "password": "123fffff"
}
###

# ПРЕДЛОЖЕНИЯ
## Получение предложений
GET http://localhost:5000/offers/ HTTP/1.1
Content-Type: application/json

###

## Получение детального предложения
GET http://localhost:5000/offers/65393031ea34f7018af34a96 HTTP/1.1

###

## Получение премиальных предложений по городу
GET http://localhost:5000/offers/premium/Dusseldorf?limit=7 HTTP/1.1

###

## Создание предложения
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

{
    "title": "My My My Super in center",
    "description": "it veeeeeeeeeeeeeeeeeery gggggoooooood Hooooooooooo Cool",
    "postDate": "2023-10-11T20:08:59.937Z",
    "city": "Paris",
    "imagePreview": "paris.jpg",
    "images": ["paris1.jpg", "paris2.jpg", "paris3.jpg", "paris4.jpg", "paris5.jpg", "paris6.jpg"],
    "premium": false,
    "favourite": false,
    "rating": 0,
    "apartmentType": "room",
    "roomCount": 4,
    "guestsCount": 2,
    "cost": 85100,
    "comfort": ["Fridge"],
    "author": "654388f403b3ca0ff2aa90b5",
    "commentsCount": 0,
    "coords": {
      "latitude": "48.85661",
      "longitude": "2.351499"
    }
}
###

## Обновление предложения
PATCH http://localhost:5000/offers/654393628639cd2060ff00ca HTTP/1.1
Content-Type: application/json

{
    "title": "New room in center of Paris"
}
###

## Удаление предложения
DELETE http://localhost:5000/offers/653ea51bf1e82a5de37c5763 HTTP/1.1
###

## Добавление в избранное
PATCH http://localhost:5000/offers/65393031ea34f7018af34a96/653e452f2e5854b16b023097 HTTP/1.1
###

## Удаление из избранного
DELETE  http://localhost:5000/offers/65393031ea34f7018af34a96/653e452f2e5854b16b023097 HTTP/1.1
###

## Получение избранных по пользователю
GET  http://localhost:5000/offers/favorite/653e452f2e5854b16b023097 HTTP/1.1
###

