# КОММЕНТАРИИ
## Получение комментариев по id предложения
GET http://localhost:5000/comments/6543906d1de6e37dbe9b4c5f HTTP/1.1
###


## Создание комментария
POST http://localhost:5000/comments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJtYWlsIjoidmFseWFAeWEubmV0IiwibmFtZSI6IlZhbHlhIiwiYXZhdGFyIjoiIiwidXNlclR5cGUiOiLQvtCx0YvRh9C90YvQuSIsImlkIjoiNjU0Mzk3NzI2NjQ3ODM5M2E2NjRmNzZjIiwiaWF0IjoxNjk5Mjc4NjgzLCJleHAiOjE2OTk0NTE0ODN9.FM4Etd9FOo8czLZdWvh6BnFOB_ngmJtb-GziJQMNBk0
Content-Type: application/json

{
  "text": "this super test comment with token",
  "rating": 5,
  "offerId": "654393628639cd2060ff00ca"
}
###


# ПОЛЬЗОВАТЕЛИ
## Создать нового пользователя
POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Nikola",
  "email": "nik@ya.net",
  "type": "pro",
  "password": "123456"
}
###

## Аутентификация  пользователя
POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "nik@ya.net",
  "password": "123456"
}
###

## Проверка пользователя
GET http://localhost:5000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5pa0B5YS5uZXQiLCJuYW1lIjoiTmlrb2xhIiwiYXZhdGFyIjoiZGVmYXVsdC1hdmF0YXIuc3ZnIiwidHlwZSI6InBybyIsImlkIjoiNjU1OWU5M2U4ODU2NTI0YWY2Njk5ZTdkIiwiaWF0IjoxNzAwMzkxMjU0LCJleHAiOjE3MDA1NjQwNTR9.mk2RIiJjtyo9PdlLxV3J_dNKyOsD16DRjYdig8tsK74
###

## Отправить изображение на аватар
POST http://localhost:5000/users/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5pa0B5YS5uZXQiLCJuYW1lIjoiTmlrb2xhIiwiYXZhdGFyIjoiZGVmYXVsdC1hdmF0YXIuc3ZnIiwidHlwZSI6InBybyIsImlkIjoiNjU1OWU5M2U4ODU2NTI0YWY2Njk5ZTdkIiwiaWF0IjoxNzAwMzkxMjU0LCJleHAiOjE3MDA1NjQwNTR9.mk2RIiJjtyo9PdlLxV3J_dNKyOsD16DRjYdig8tsK74
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="foto.jpeg"
Content-Type: image/jpeg

< /Users/Nikolay/Desktop/foto.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# ПРЕДЛОЖЕНИЯ
## Получение предложений
GET http://localhost:5000/offers/ HTTP/1.1
Content-Type: application/json

###

## Получение детального предложения
GET http://localhost:5000/offers/6543906d1de6e37dbe9b4c5f HTTP/1.1

###

## Получение премиальных предложений по городу
GET http://localhost:5000/offers/premium/Paris?limit=7 HTTP/1.1

###

## Создание предложения
POST http://localhost:5000/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5pa0B5YS5uZXQiLCJuYW1lIjoiTmlrb2xhIiwiYXZhdGFyIjoiZGVmYXVsdC1hdmF0YXIuc3ZnIiwidHlwZSI6InBybyIsImlkIjoiNjU1OWU5M2U4ODU2NTI0YWY2Njk5ZTdkIiwiaWF0IjoxNzAwMzkxMjU0LCJleHAiOjE3MDA1NjQwNTR9.mk2RIiJjtyo9PdlLxV3J_dNKyOsD16DRjYdig8tsK74
Content-Type: application/json

{
    "title": "Raaaaaaaaaaaaaaaaaaaa kaaaaaaaa buuuuum",
    "description": "The Flying Pig Downtown Hostel",
    "postDate": "2023-10-11T20:08:59.937Z",
    "city": "Paris",
    "imagePreview": "Paris.jpg",
    "images": ["amsterdam.jpg", "amsterdam.jpg", "amsterdam.jpg", "amsterdam.jpg", "amsterdam.jpg", "amsterdam.jpg"],
    "premium": false,
    "favourite": false,
    "rating": 0,
    "apartmentType": "hotel",
    "roomCount": 2,
    "guestsCount": 3,
    "cost": 87100,
    "comfort": ["Breakfast", "Fridge", "Baby seat"],
    "commentsCount": 0,
    "coords": {
      "latitude": "48.85661",
      "longitude": "2.351499"
    }
}
###

## Обновление предложения
PATCH http://localhost:5000/offers/6559ea22f0f573cebda25a72 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5pa0B5YS5uZXQiLCJuYW1lIjoiTmlrb2xhIiwiYXZhdGFyIjoiZGVmYXVsdC1hdmF0YXIuc3ZnIiwidHlwZSI6InBybyIsImlkIjoiNjU1OWU5M2U4ODU2NTI0YWY2Njk5ZTdkIiwiaWF0IjoxNzAwMzkxMjU0LCJleHAiOjE3MDA1NjQwNTR9.mk2RIiJjtyo9PdlLxV3J_dNKyOsD16DRjYdig8tsK74
Content-Type: application/json

{
    "title": "New room in center of Paris"
}
###

## Удаление предложения
DELETE http://localhost:5000/offers/654cdd02ad1e5f8a4e96bd4d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJtYWlsIjoibmlja0B5YS5uZXQiLCJuYW1lIjoiTmlja29sYSIsImF2YXRhciI6IiIsInVzZXJUeXBlIjoicHJvIiwiaWQiOiI2NTRhM2Y5NWE3NTM3YjZiNTAyMTI0NTUiLCJpYXQiOjE2OTk1MjM2MDAsImV4cCI6MTY5OTY5NjQwMH0.5AZ_xNFaNJduDq8aNC0xPublp8ih2AinL3fC_T5nocc
###

## Добавление предложения в избранное
PATCH http://localhost:5000/offers/6543906d1de6e37dbe9b4c5f/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJtYWlsIjoibmlja0B5YS5uZXQiLCJuYW1lIjoiTmlja29sYSIsImF2YXRhciI6Im5pY2tvbC5wbmciLCJ1c2VyVHlwZSI6InBybyIsImlkIjoiNjU0Mzg4ZjQwM2IzY2EwZmYyYWE5MGI1IiwiaWF0IjoxNjk5ODk1OTE0LCJleHAiOjE3MDAwNjg3MTR9.oY0DIezZr4IcALOwUq91xufI0zba51vTPnS2r29BeNs
###

## Удаление предложения из избранного
DELETE  http://localhost:5000/offers/6543906d1de6e37dbe9b4c5f/favorite HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJtYWlsIjoibmlja0B5YS5uZXQiLCJuYW1lIjoiTmlja29sYSIsImF2YXRhciI6Im5pY2tvbC5wbmciLCJ1c2VyVHlwZSI6InBybyIsImlkIjoiNjU0Mzg4ZjQwM2IzY2EwZmYyYWE5MGI1IiwiaWF0IjoxNjk5ODk1OTE0LCJleHAiOjE3MDAwNjg3MTR9.oY0DIezZr4IcALOwUq91xufI0zba51vTPnS2r29BeNs
###

## Получение избранных предложений по пользователю
GET  http://localhost:5000/offers/favorite/offers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJtYWlsIjoibmlja0B5YS5uZXQiLCJuYW1lIjoiTmlja29sYSIsImF2YXRhciI6Im5pY2tvbC5wbmciLCJ1c2VyVHlwZSI6InBybyIsImlkIjoiNjU0Mzg4ZjQwM2IzY2EwZmYyYWE5MGI1IiwiaWF0IjoxNjk5ODk1OTE0LCJleHAiOjE3MDAwNjg3MTR9.oY0DIezZr4IcALOwUq91xufI0zba51vTPnS2r29BeNs
###

## Отправить изображения для предложения
POST http://localhost:5000/offers/6550954d099643a7f1b710da/images HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJtYWlsIjoibmFkYUB5YS5uZXQiLCJuYW1lIjoiTmFkb21hbiIsImF2YXRhciI6IlNVSWl0blU3OTJOdkR1MTdZaWVpZy5qcGVnIiwidXNlclR5cGUiOiJwcm8iLCJpZCI6IjY1NGZiZDdiOWJiMWFkNzdlZTMwMzMzZSIsImlhdCI6MTY5OTc4MDQxNiwiZXhwIjoxNjk5OTUzMjE2fQ.rISGHoqvod23-919lxv-v1DprXTS0bjK8bYd7_e0m6E
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="foto.jpeg"
Content-Type: image/jpeg

< /Users/Nikolay/Desktop/foto.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="foto2.jpeg"
Content-Type: image/jpeg

< /Users/Nikolay/Desktop/foto2.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="foto2.jpeg"
Content-Type: image/jpeg

< /Users/Nikolay/Desktop/foto2.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="foto2.jpeg"
Content-Type: image/jpeg

< /Users/Nikolay/Desktop/foto2.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="foto2.jpeg"
Content-Type: image/jpeg

< /Users/Nikolay/Desktop/foto2.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="foto2.jpeg"
Content-Type: image/jpeg

< /Users/Nikolay/Desktop/foto2.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Отправить изображение-первью для предложения
POST http://localhost:5000/offers/6559ea22f0f573cebda25a72/preview HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im5pa0B5YS5uZXQiLCJuYW1lIjoiTmlrb2xhIiwiYXZhdGFyIjoiZGVmYXVsdC1hdmF0YXIuc3ZnIiwidHlwZSI6InBybyIsImlkIjoiNjU1OWU5M2U4ODU2NTI0YWY2Njk5ZTdkIiwiaWF0IjoxNzAwMzkxMjU0LCJleHAiOjE3MDA1NjQwNTR9.mk2RIiJjtyo9PdlLxV3J_dNKyOsD16DRjYdig8tsK74
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="imagePreview"; filename="foto.jpeg"
Content-Type: image/jpeg

< /Users/Nikolay/Desktop/foto2.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
